/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import newpackage.Film;

/**
 *
 * @author javier
 */
public class MainWindow extends javax.swing.JFrame {
    private String busqueda;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private List<Film> peliculas;
    private Controlador controlador;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        iniciarComponentes();
    }
    
    public void iniciarComponentes(){
        busqueda = "";
        peliculas = null;
        controlador = new Controlador();
        iniciarTabla();
        actionButtonListar();
    }
    
    public void iniciarTabla(){
        modeloTabla.addColumn("Título");
        modeloTabla.addColumn("Año");
        modeloTabla.addColumn("Duración");
        modeloTabla.addColumn("Características");
        
        tabla.setModel(modeloTabla);
    }
    
    public void actualizarTabla(){
        limpiarTabla();
        
        for(Film f: peliculas){
            modeloTabla.addRow(new Object[]{f.getTitle(), f.getReleaseYear(), 
                f.getLength(), f.getSpecialFeatures()});
        }
    }
    
    public void limpiarTabla(){
        int rows = modeloTabla.getRowCount();
        
        for(int i=0;i<rows;i++){
            modeloTabla.removeRow(0);
        }
    }
    
    public void listar(){
        peliculas = controlador.listar();
    }
    
    public void actionButtonListar(){
        listar();
        actualizarTabla();
    }
    
    public void buscarNombre(){
        peliculas = controlador.buscarPeliculas(busqueda);
    }
    
    public void actionButtonBuscarNombre(){
        IntroducirBusqueda dialogoBusqueda = new IntroducirBusqueda(this, true);
        dialogoBusqueda.setVisible(true);
        
        if(dialogoBusqueda.getAceptarCancelar() > 0){
            busqueda = dialogoBusqueda.getBusqueda();
            buscarNombre();
            actualizarTabla();
        }
    }
    
    public void buscarCategoria(){
        peliculas = controlador.buscarPorCategoria(busqueda);
    }
    
    public void actionButtonBuscarCategoria(){
        ElegirCaracteristica ec = new ElegirCaracteristica(this, true, controlador.arrayCategorias());
        ec.setVisible(true);
        
        if(ec.getAceptarCancelar() > 0){
            busqueda = ec.getSelectedItem();
            buscarCategoria();
            actualizarTabla();
        }
    }
    
    public void buscarCaracteristica(){
        peliculas = controlador.buscarPorCaracteristicasEspeciales(busqueda);
    }
    
    public void actionButtonBuscarCaracteristicas(){
        ElegirCaracteristica ec = new ElegirCaracteristica(this, true, controlador.distinctCaracteristicas());
        ec.setVisible(true);
        
        if(ec.getAceptarCancelar() > 0){
            busqueda = ec.getSelectedItem();
            buscarCaracteristica();
            actualizarTabla();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        buttonListar = new javax.swing.JButton();
        buttonNombre = new javax.swing.JButton();
        buttonCategoria = new javax.swing.JButton();
        buttonCaracteristicas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        buttonListar.setText("Listar todas");
        buttonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarActionPerformed(evt);
            }
        });

        buttonNombre.setText("Buscar por Nombre");
        buttonNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNombreActionPerformed(evt);
            }
        });

        buttonCategoria.setText("Buscar por Categoría");
        buttonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCategoriaActionPerformed(evt);
            }
        });

        buttonCaracteristicas.setText("Buscar por Características Especiales");
        buttonCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCaracteristicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonListar)
                    .addComponent(buttonNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCategoria)
                    .addComponent(buttonCaracteristicas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarActionPerformed
        actionButtonListar();
    }//GEN-LAST:event_buttonListarActionPerformed

    private void buttonNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNombreActionPerformed
        actionButtonBuscarNombre();
    }//GEN-LAST:event_buttonNombreActionPerformed

    private void buttonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCategoriaActionPerformed
        actionButtonBuscarCategoria();
    }//GEN-LAST:event_buttonCategoriaActionPerformed

    private void buttonCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCaracteristicasActionPerformed
        actionButtonBuscarCaracteristicas();
    }//GEN-LAST:event_buttonCaracteristicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCaracteristicas;
    private javax.swing.JButton buttonCategoria;
    private javax.swing.JButton buttonListar;
    private javax.swing.JButton buttonNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
